"""Event type constants — adapted from CLF core/events.py for chat app."""
# Message lifecycle
MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
MESSAGE_SENT = "MESSAGE_SENT"

# Time & scene
TIME_ADVANCE = "TIME_ADVANCE"            # narrative clock ticked forward
SCENE_TRANSITION = "SCENE_TRANSITION"    # scene changed (e.g. 天台 -> 家)

# Emotion (Phase 2)
EMOTION_UPDATED = "EMOTION_UPDATED"
EMOTION_CONFLICT = "EMOTION_CONFLICT"

# Memory (Phase 3)
MEMORY_ENCODE = "MEMORY_ENCODE"
MEMORY_CONSOLIDATED = "MEMORY_CONSOLIDATED"

# Character
CHARACTER_SWITCHED = "CHARACTER_SWITCHED"
PERSONALITY_UPDATE = "PERSONALITY_UPDATE"

ALL_TYPES = [
    MESSAGE_RECEIVED, MESSAGE_SENT,
    TIME_ADVANCE, SCENE_TRANSITION,
    EMOTION_UPDATED, EMOTION_CONFLICT,
    MEMORY_ENCODE, MEMORY_CONSOLIDATED,
    CHARACTER_SWITCHED, PERSONALITY_UPDATE,
]
